In [1]:
import numpy as np 

In [2]:
a = [[2,1,1],[3,2,1],[2,1,2]]
c = np.linalg.inv(a)
c

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])

In [3]:
b2 = [[2,-2],[1,1]]
m = np.linalg.inv(b2)

In [4]:
m

array([[ 0.25,  0.5 ],
       [-0.25,  0.5 ]])

In [5]:
m @ [8,6]

array([5., 1.])

In [6]:
b2 = [[1,1],[-2,1]]
m = np.linalg.inv(b2)

In [7]:
m

array([[ 0.33333333, -0.33333333],
       [ 0.66666667,  0.33333333]])

In [8]:
m @ [25,28]

array([-1., 26.])

In [12]:
 m = b2

In [17]:
m

[[1, 1], [-2, 1]]

In [20]:
b2 = [[3,-3],[4,-5]]
m = np.linalg.inv(b2)

In [21]:
m

array([[ 1.66666667, -1.        ],
       [ 1.33333333, -1.        ]])

In [22]:
m @ [3,2]

array([3., 2.])